const express=require("express")
const dotenv=require("dotenv")
const connectionDB =require("./config/db")
const AuthRoutes=require('./routes/AuthRoutes')
const AdminRoutes=require("./routes/AdminRoutes")
const visitorRoutes=require("./routes/VisitorRoutes")
const employeeRoutes=require("./routes/EmployeeRoutes")
const securityRoutes=require("./routes/SecurityRoutes")
dotenv.config()
const server=express()
server.use(express.json())
connectionDB()
server.get('/',(req,res)=>{
    res.send("Hello From the Backend Server and Buddy")
})
server.use('/api/users',AuthRoutes)
server.use('/api/admin',AdminRoutes)
server.use('/api/users/visitor',visitorRoutes)
server.use('/api/users/employee',employeeRoutes)
server.use('/api/users/security',securityRoutes)
const PORT=process.env.PORT || 8080

server.listen(PORT,()=>{
    console.log(`server is running on http://localhost:${PORT}`)
})